
# Setup
title:               Jekyll Example
tagline:             Basic example of a Jekyll site with Sass enabled.
url:                 http://mdo.github.io/jekyll-example
baseurl:             /

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed
